//! Port of `Clipboard/ClipboardMonitor.swift`.
//!
//! Polls NSPasteboard.general.changeCount (macOS has no change notification).
//! Reading one integer twice a second is the standard approach and costs
//! nothing measurable.
//!
//! Swift's state lives on the main actor; here the state is a plain Mutex —
//! the timer fires on the main run loop and the workspace/lock notifications
//! arrive on arbitrary threads, so the mutex (not the actor) is the isolation.
//! ObjC objects the state holds (timer, observer tokens) are stored as raw
//! retained pointers: they are alive for the process lifetime and only ever
//! touched under the lock.

use std::path::PathBuf;
use std::sync::{Mutex, OnceLock};

use objc2::rc::Retained;
use objc2::runtime::{AnyClass, AnyObject};
use objc2::{class, msg_send};
use objc2_app_kit::{NSBitmapImageRep, NSPasteboard, NSWorkspace};
use objc2_foundation::{
    ns_string, NSArray, NSDictionary, NSDistributedNotificationCenter, NSData, NSNotification,
    NSString, NSTimer,
};

use crate::app::preferences::Preferences;
use crate::capture::pasteboard_writer;
use crate::capture::screenshotter;
use crate::clipboard::item::{now, ClipItem};
use crate::clipboard::store::{self, Source};

const SKIP_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
];

/// Apps whose copies are secrets by default. Most password managers mark
/// their copies with the "concealed" pasteboard type above; Apple's Passwords
/// app does not, so the source app is checked too.
const PASSWORD_MANAGER_BUNDLES: &[&str] = &[
    "com.apple.passwords",
    "com.apple.keychainaccess",
    "com.1password.1password",
    "com.agilebits.onepassword7",
    "com.agilebits.onepassword-osx",
    "com.bitwarden.desktop",
    "org.keepassxc.keepassxc",
    "in.sinew.enpass-desktop",
    "com.lastpass.lastpass",
    "com.dashlane.dashlane",
    "com.nordpass.macos",
    "me.proton.pass.macos",
];
const PASSWORD_MANAGER_SUBSTRINGS: &[&str] = &[
    "password", "keepass", "bitwarden", "enpass", "dashlane", "lastpass", "nordpass",
    "strongbox", "protonpass",
];

pub fn is_password_manager(bundle_id: Option<&str>) -> bool {
    let Some(id) = bundle_id.map(|s| s.to_ascii_lowercase()) else {
        return false;
    };
    if PASSWORD_MANAGER_BUNDLES.contains(&id.as_str()) {
        return true;
    }
    PASSWORD_MANAGER_SUBSTRINGS.iter().any(|s| id.contains(s))
}

/// Bitmap plus exactly one image file: a screenshot handed over. (Finder
/// copies files without bitmap data.)
fn is_screenshot_handoff(urls: &[PathBuf]) -> bool {
    urls.len() == 1 && is_image_file(&urls[0])
}

fn is_image_file(p: &PathBuf) -> bool {
    matches!(
        p.extension()
            .map(|e| e.to_string_lossy().to_lowercase())
            .as_deref(),
        Some("png" | "jpg" | "jpeg" | "tiff" | "tif" | "heic" | "gif" | "webp" | "bmp")
    )
}

fn is_temporary(p: &PathBuf) -> bool {
    let s = p.to_string_lossy();
    s.contains("/T/")
        || s.starts_with("/tmp")
        || s.starts_with("/private/tmp")
        || s.contains("/Caches/")
        || s.contains("/Library/Containers/")
}

/// NSBitmapImageRep is MainThreadOnly in the bindings; allocation needs a marker.
fn alloc_bitmap_rep() -> objc2::rc::Allocated<NSBitmapImageRep> {
    match objc2::MainThreadMarker::new() {
        Some(mtm) => mtm.alloc::<NSBitmapImageRep>(),
        // Ingest runs on the main thread in every caller (monitor, self-tests).
        None => unreachable!("bitmap rep off the main thread"),
    }
}

/// NSBitmapImageRep keeps the embedded profile when re-encoding.
fn png_from_tiff(tiff: &[u8]) -> Option<Vec<u8>> {
    let data = NSData::with_bytes(tiff);
    let rep = NSBitmapImageRep::initWithData(alloc_bitmap_rep(), &data)?;
    let props = NSDictionary::<NSString, AnyObject>::new();
    let png = unsafe { rep.representationUsingType_properties(objc2_app_kit::NSBitmapImageFileType::PNG, &props) }?;
    Some(png.to_vec())
}

/// File URLs on the board (`readObjects(forClasses: [NSURL.self], options:
/// [.urlReadingFileURLsOnly: true])`).
pub fn read_file_urls(pb: &NSPasteboard) -> Vec<PathBuf> {
    unsafe {
        let Some(cls) = AnyClass::get(c"NSURL") else { return Vec::new() };
        let classes = NSArray::<AnyClass>::from_slice(&[cls]);
        let value: Retained<AnyObject> = msg_send![class!(NSNumber), numberWithBool: true];
        // SAFETY: NSNumber is a regular plist value for this options key.
        let options = NSDictionary::from_slices(
            &[objc2_app_kit::NSPasteboardURLReadingFileURLsOnlyKey],
            &[&*value as &AnyObject],
        );
        let Some(arr) = pb.readObjectsForClasses_options(&classes, Some(&options)) else {
            return Vec::new();
        };
        let mut out = Vec::new();
        for obj in arr.iter() {
            let path: Option<Retained<NSString>> = msg_send![&*obj, path];
            if let Some(p) = path {
                out.push(PathBuf::from(p.to_string()));
            }
        }
        out
    }
}

/// Reads the board into the store. Returns the resulting item (new or
/// bumped). Taken verbatim from `ClipboardMonitor.ingest`; the rule order is
/// the behavior (red line 10).
pub fn ingest(pb: &NSPasteboard) -> Option<ClipItem> {
    let types: Vec<String> = pb
        .types()
        .map(|t| t.iter().map(|s| s.to_string()).collect())
        .unwrap_or_default();
    // 1. Our own marker: a Pastory copy went back on the board → bump.
    if types.iter().any(|t| t == "com.cici.snipclip.marker") {
        if let Some(id) = pb.stringForType(pasteboard_writer::marker()) {
            store::with(|st| st.bump(&id.to_string()));
            return store::read(|s| s.items.first().cloned());
        }
    }
    // 2. Concealed / transient / auto-generated: never record.
    if SKIP_TYPES.iter().any(|s| types.iter().any(|t| t == s)) {
        return None;
    }
    let source = Source::frontmost();
    if !Preferences::shared().record_password_managers() {
        if is_password_manager(source.bundle_id.as_deref()) {
            return None;
        }
        let st = state().lock().unwrap();
        if let Some((bundle, until)) = &st.previous_front {
            // A copy made in a password manager followed by an immediate ⌘-Tab
            // would otherwise be attributed to the next app.
            if now() - until < 1.5 && is_password_manager(bundle.as_deref()) {
                return None;
            }
        }
    }

    let has_bitmap = types.iter().any(|t| t == "public.png" || t == "public.tiff");
    let urls = read_file_urls(pb);
    // 3. Other screenshot tools (WeChat, Feishu, CleanShot…) put the picture
    // on the board together with a file URL to their own temp copy. That is a
    // picture, not a "file": keep the bitmap so it gets a thumbnail and OCR.
    if has_bitmap && (urls.is_empty() || is_screenshot_handoff(&urls)) {
        let png = pb
            .dataForType(pasteboard_writer::t_png())
            .map(|d| d.to_vec())
            .or_else(|| {
                pb.dataForType(pasteboard_writer::t_tiff())
                    .and_then(|d| png_from_tiff(&d.to_vec()))
            });
        if let Some(png) = png {
            return store::with(|s| s.insert_image(&png, &source, None));
        }
    }
    // 4. A tool copied only a temp image file: same thing — decode it.
    if urls.len() == 1 && is_image_file(&urls[0]) && is_temporary(&urls[0]) {
        if let Ok(data) = std::fs::read(&urls[0]) {
            if let Some(png) = screenshotter::png_data_from_image_bytes(&data) {
                return store::with(|s| s.insert_image(&png, &source, None));
            }
        }
    }
    // 5. Everything else with file URLs is a plain file reference.
    if !urls.is_empty() {
        return store::with(|s| s.insert_files(&urls, &source));
    }
    // 6. Text (with optional rtf), finally a bare URL string.
    if let Some(s) = pb.stringForType(pasteboard_writer::t_string()) {
        let rtf = pb.dataForType(pasteboard_writer::t_rtf()).map(|d| d.to_vec());
        return store::with(|st| st.insert_text(&s.to_string(), rtf.as_deref(), &source));
    }
    if let Some(s) = pb.stringForType(pasteboard_writer::t_url()) {
        return store::with(|st| st.insert_text(&s.to_string(), None, &source));
    }
    None
}

// MARK: Monitor state (timer, lock screen, front-app tracking)

struct State {
    last_count: isize,
    locked: bool,
    /// The app that was frontmost just before the current one, with the time
    /// it lost the front.
    previous_front: Option<(Option<String>, f64)>,
    current_front: Option<String>,
    timer: Option<usize>,
    on_change: Option<Box<dyn FnMut(&ClipItem) + Send>>,
}

fn state() -> &'static Mutex<State> {
    static STATE: OnceLock<Mutex<State>> = OnceLock::new();
    STATE.get_or_init(|| {
        let count = NSPasteboard::generalPasteboard().changeCount();
        let front = NSWorkspace::sharedWorkspace()
            .frontmostApplication()
            .and_then(|a| a.bundleIdentifier())
            .map(|b| b.to_string());
        Mutex::new(State {
            last_count: count,
            locked: false,
            previous_front: None,
            current_front: front,
            timer: None,
            on_change: None,
        })
    })
}

pub fn start() {
    register_observers_once();
    {
        let mut st = state().lock().unwrap();
        if st.timer.is_some() {
            return;
        }
        st.last_count = NSPasteboard::generalPasteboard().changeCount();
    }
    unsafe {
        let block = block2::RcBlock::new(|_: std::ptr::NonNull<NSTimer>| tick());
        let t = NSTimer::timerWithTimeInterval_repeats_block(0.5, true, &block);
        t.setTolerance(0.2);
        // Common modes: keeps polling while a menu is tracked, like the Swift version.
        let mode: &'static objc2_foundation::NSRunLoopMode = objc2_foundation::NSRunLoopCommonModes;
        objc2_foundation::NSRunLoop::mainRunLoop().addTimer_forMode(&t, mode);
        state().lock().unwrap().timer = Some(Retained::into_raw(t) as usize);
    }
}

pub fn stop() {
    let ptr = state().lock().unwrap().timer.take();
    if let Some(p) = ptr {
        // SAFETY: retained in `start`; invalidated and released here exactly once.
        unsafe {
            let t: Retained<NSTimer> = Retained::from_raw(p as *mut NSTimer).expect("live timer");
            t.invalidate();
        }
    }
}

pub fn set_on_change(cb: Option<Box<dyn FnMut(&ClipItem) + Send>>) {
    state().lock().unwrap().on_change = cb;
}

/// Main-thread confinement is NOT required: reads go through `state()`.
pub fn is_running() -> bool {
    state().lock().unwrap().timer.is_some()
}

fn tick() {
    let pb = NSPasteboard::generalPasteboard();
    let count = pb.changeCount();
    {
        let mut st = state().lock().unwrap();
        if count == st.last_count {
            return;
        }
        st.last_count = count;
        if st.locked || Preferences::shared().monitoring_paused() {
            return;
        }
    }
    if let Some(item) = ingest(&pb) {
        // M2: text/url copies tick the welcome checklist ("copy").
        let mut st = state().lock().unwrap();
        if let Some(cb) = st.on_change.as_mut() {
            cb(&item);
        }
    }
}

fn register_observers_once() {
    use std::sync::Once;
    static ONCE: Once = Once::new();
    ONCE.call_once(|| unsafe {
        // Front-app tracking for password-manager attribution.
        let center = NSWorkspace::sharedWorkspace().notificationCenter();
        let block = block2::RcBlock::new(|n: std::ptr::NonNull<NSNotification>| {
            let front = frontmost_from_notification(n);
            let mut st = state().lock().unwrap();
            st.previous_front = Some((st.current_front.take(), now()));
            st.current_front = front;
        });
        let obs = center.addObserverForName_object_queue_usingBlock(
            Some(objc2_app_kit::NSWorkspaceDidActivateApplicationNotification),
            None,
            None,
            &block,
        );
        // Observers live for the process lifetime (Swift never removes them either).
        std::mem::forget(obs);

        // Screen lock: nothing recorded while locked, and the changeCount
        // delta across the lock is ignored on unlock.
        let dnc = NSDistributedNotificationCenter::defaultCenter();
        let lock_block = block2::RcBlock::new(|_: std::ptr::NonNull<NSNotification>| {
            state().lock().unwrap().locked = true;
        });
        let unlock_block = block2::RcBlock::new(|_: std::ptr::NonNull<NSNotification>| {
            let mut st = state().lock().unwrap();
            st.locked = false;
            // Ignore whatever happened while locked.
            st.last_count = NSPasteboard::generalPasteboard().changeCount();
        });
        let locked_name = NSString::from_str("com.apple.screenIsLocked");
        let unlocked_name = NSString::from_str("com.apple.screenIsUnlocked");
        let o1 = dnc.addObserverForName_object_queue_usingBlock(
            Some(&locked_name),
            None,
            None,
            &lock_block,
        );
        let o2 = dnc.addObserverForName_object_queue_usingBlock(
            Some(&unlocked_name),
            None,
            None,
            &unlock_block,
        );
        std::mem::forget(o1);
        std::mem::forget(o2);
    });
}

/// `userInfo[NSWorkspaceApplicationUserInfoKey].bundleIdentifier`.
unsafe fn frontmost_from_notification(n: std::ptr::NonNull<NSNotification>) -> Option<String> {
    let n = unsafe { n.as_ref() };
    let info = n.userInfo()?;
    let obj = info.objectForKey(ns_string!("NSWorkspaceApplicationUserInfoKey"))?;
    let bid: Option<Retained<NSString>> = msg_send![&*obj, bundleIdentifier];
    bid.map(|s| s.to_string())
}
