//! Port of the M1 `SelfTest.swift` commands: pbtypes, pbfiles, clipboard,
//! ingest, retention, tombstone, heic, writer. Each mirrors its Swift twin's
//! checks and output shape; mutating ones only ever see PASTORY_STORE (the
//! gating lives in selftest.rs).

use std::path::{Path, PathBuf};

use objc2::rc::Retained;
use objc2::msg_send;
use objc2_app_kit::NSPasteboard;
use objc2_core_graphics as cg;
use objc2_foundation::{NSArray, NSData, NSDate, NSRunLoop, NSString, NSUUID, NSURL};

use crate::app::preferences::Preferences;
use crate::capture::{pasteboard_writer, screenshotter};
use crate::clipboard::item::{now, start_of_day, ClipItem, ClipKind};
use crate::clipboard::store::{ClipStore, Source};
use crate::clipboard::{importer, monitor, retention, store};

const PREMULTIPLIED_LAST: u32 = 1;

/// A file that exists in any checkout (Swift `SelfTest.sampleFile`).
pub fn sample_file() -> PathBuf {
    let p = PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/../Package.swift"));
    p.canonicalize().unwrap_or(p)
}

fn report(ok: &mut bool, name: &str, cond: bool) {
    println!("{} {}", if cond { "ok  " } else { "FAIL" }, name);
    *ok &= cond;
}

fn clear_store() {
    store::with(|s| {
        let ids: Vec<String> = s.items.iter().map(|i| i.id.clone()).collect();
        s.remove_ids(&ids);
    });
}

fn uuid() -> String {
    NSUUID::new().UUIDString().to_string()
}

/// Pump the main run loop (timers fire, pastes land) for `seconds`.
fn pump(seconds: f64) {
    let rl = NSRunLoop::mainRunLoop();
    let deadline = retention::now_ts() + seconds;
    while retention::now_ts() < deadline {
        let limit = NSDate::dateWithTimeIntervalSinceNow(0.05);
        // SAFETY: NSDefaultRunLoopMode is a valid mode token.
        let mode: &'static objc2_foundation::NSRunLoopMode =
            unsafe { objc2_foundation::NSDefaultRunLoopMode };
        rl.runMode_beforeDate(mode, &limit);
    }
}

/// An RGBA8 bitmap encoded as PNG, pixel values from `px`, in `space`.
fn bitmap_png(
    w: usize,
    h: usize,
    space: &cg::CGColorSpace,
    px: impl Fn(usize, usize) -> [u8; 4],
) -> Option<(Vec<u8>, objc2_core_foundation::CFRetained<cg::CGImage>)> {
    let mut buf = vec![0u8; w * h * 4];
    for y in 0..h {
        for x in 0..w {
            let o = (y * w + x) * 4;
            buf[o..o + 4].copy_from_slice(&px(x, y));
        }
    }
    // SAFETY: `buf` outlives the context and image creation below.
    let ctx = unsafe {
        cg::CGBitmapContextCreate(
            buf.as_mut_ptr().cast(),
            w,
            h,
            8,
            w * 4,
            Some(space),
            PREMULTIPLIED_LAST,
        )
    }?;
    let image = cg::CGBitmapContextCreateImage(Some(&ctx))?;
    let png = screenshotter::png_data(&image)?;
    Some((png, image))
}

// MARK: pbtypes — read-only view of the general pasteboard

pub fn pbtypes() -> bool {
    let pb = NSPasteboard::generalPasteboard();
    let types: Vec<String> = pb
        .types()
        .map(|t| t.iter().map(|s| s.to_string()).collect())
        .unwrap_or_default();
    println!("changeCount {}, {} types:", pb.changeCount(), types.len());
    for t in &types {
        println!("  {t}");
    }
    let markers = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ];
    let present: Vec<&str> = markers
        .into_iter()
        .filter(|m| types.iter().any(|t| t == m))
        .collect();
    println!("skip markers present: {present:?}");
    let app = objc2_app_kit::NSWorkspace::sharedWorkspace()
        .frontmostApplication()
        .and_then(|a| a.bundleIdentifier())
        .map(|b| b.to_string())
        .unwrap_or_else(|| "?".into());
    println!("source app: {app}");
    true
}

// MARK: pbfiles — write a file item the way Finder would

pub fn pbfiles(rest: &[String]) -> bool {
    let path = rest.first().map(PathBuf::from).unwrap_or_else(sample_file);
    pasteboard_writer::write_files(&[path], "test");
    let pb = NSPasteboard::generalPasteboard();
    let types: Vec<String> = pb
        .types()
        .map(|t| t.iter().map(|s| s.to_string()).collect())
        .unwrap_or_default();
    println!("{}", types.join("\n"));
    let urls = monitor::read_file_urls(&pb);
    let names: Vec<String> = urls
        .iter()
        .map(|u| {
            u.file_name()
                .map(|n| n.to_string_lossy().into_owned())
                .unwrap_or_default()
        })
        .collect();
    println!("readObjects → {names:?}");
    urls.len() == 1
}

// MARK: clipboard — listen to the real pasteboard for N seconds

pub fn clipboard(rest: &[String]) -> bool {
    let seconds: f64 = rest
        .first()
        .and_then(|s| s.parse().ok())
        .unwrap_or(10.0);
    println!("store: {}", store::read(|s| s.root.display().to_string()));
    println!(
        "listening {}s — copy some text, an image, a file in Finder…",
        seconds as i64
    );
    let seen = std::sync::Arc::new(std::sync::atomic::AtomicUsize::new(0));
    let seen2 = seen.clone();
    monitor::set_on_change(Some(Box::new(move |item: &ClipItem| {
        seen2.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        let src = item.source_app_name.clone().unwrap_or_else(|| "?".into());
        let snip: String = item.snippet.replace('\n', " ⏎ ").chars().take(60).collect();
        println!("  + {:<6} {}  {}", item.kind.raw(), src, snip);
    })));
    monitor::start();
    pump(seconds);
    monitor::stop();
    monitor::set_on_change(None);
    let n = seen.load(std::sync::atomic::Ordering::Relaxed);
    println!(
        "recorded {} item(s); store now holds {}",
        n,
        store::read(|s| s.items.len())
    );
    true
}

// MARK: ingest — what other tools put on the board lands as the right kind

fn write_url_objects(pb: &NSPasteboard, paths: &[&Path]) {
    let urls: Vec<Retained<NSURL>> = paths
        .iter()
        .map(|p| {
            NSURL::fileURLWithPath_isDirectory(&NSString::from_str(&p.to_string_lossy()), p.is_dir())
        })
        .collect();
    let arr = NSArray::from_retained_slice(&urls);
    // SAFETY: NSURL implements NSPasteboardWriting.
    unsafe {
        let _: bool = msg_send![pb, writeObjects: &*arr];
    }
}

fn board(fill: &dyn Fn(&NSPasteboard)) -> Option<ClipItem> {
    let name = format!("pastory.selftest.{}", uuid());
    let pb = NSPasteboard::pasteboardWithName(&NSString::from_str(&name));
    pb.clearContents();
    fill(&pb);
    let r = monitor::ingest(&pb);
    // The binding omits releaseGlobally; it's a no-selector-risk send.
    let _: () = unsafe { msg_send![&pb, releaseGlobally] };
    r
}

pub fn ingest() -> bool {
    let mut ok = true;
    store::read(|s| s.last_save_failed);
    clear_store();
    let space = match cg::CGColorSpace::with_name(Some(unsafe { cg::kCGColorSpaceSRGB })) {
        Some(s) => s,
        None => return false,
    };
    let Some((png, _)) = bitmap_png(40, 30, &space, |_, _| [255, 128, 0, 255]) else {
        println!("FAIL swatch render");
        return false;
    };
    let tmp = std::env::temp_dir().join(format!("pastory-ingest-{}.png", uuid()));
    if std::fs::write(&tmp, &png).is_err() {
        return false;
    }
    let mut check = |name: &str, item: Option<ClipItem>, want: ClipKind| {
        let got = item.map(|i| i.kind.raw()).unwrap_or("nil");
        let good = got == want.raw();
        println!("{} {name}: {got} (want {})", if good { "ok  " } else { "FAIL" }, want.raw());
        if !good {
            ok = false;
        }
        clear_store();
    };
    // bitmap + temp file url (WeChat / Feishu style)
    let item = board(&|pb: &NSPasteboard| {
        pb.setData_forType(Some(&NSData::with_bytes(&png)), pasteboard_writer::t_png());
        write_url_objects(pb, &[tmp.as_path()]);
    });
    check("bitmap + temp file url (WeChat / Feishu style)", item, ClipKind::Image);
    // finder copy of a document
    let sample = sample_file();
    let item = board(&|pb: &NSPasteboard| write_url_objects(pb, &[sample.as_path()]));
    check("finder copy of a document", item, ClipKind::Files);
    // lone temp image file
    let item = board(&|pb: &NSPasteboard| write_url_objects(pb, &[tmp.as_path()]));
    check("lone temp image file", item, ClipKind::Image);
    // plain text
    let item = board(&|pb: &NSPasteboard| {
        pb.setString_forType(&NSString::from_str("hello"), pasteboard_writer::t_string());
    });
    check("plain text", item, ClipKind::Text);
    // bitmap only
    let item = board(&|pb: &NSPasteboard| {
        pb.setData_forType(Some(&NSData::with_bytes(&png)), pasteboard_writer::t_png());
    });
    check("bitmap only", item, ClipKind::Image);
    let _ = std::fs::remove_file(&tmp);
    clear_store();
    ok
}

// MARK: retention — calendar-day rules, idempotence, tombstone reload, timer

pub fn retention() -> bool {
    use crate::clipboard::retention::{add_days, set_hour};
    let src = Source {
        bundle_id: None,
        name: Some("test".into()),
    };
    let at = |day_offset: i64, hour: i64, minute: i64| -> f64 {
        let today = start_of_day(now());
        set_hour(add_days(today, day_offset), hour, minute, 0.0)
    };
    let seed = || {
        clear_store();
        let rows: [(&str, f64, bool); 7] = [
            ("dayBefore", at(-2, 15, 0), false),
            ("yesterday", at(-1, 15, 0), false),
            ("yesterdayPinned", at(-1, 16, 0), true),
            ("today0001", at(0, 0, 1), false),
            ("today0130", at(0, 1, 30), false),
            ("today0300", at(0, 3, 0), false),
            ("today0900", at(0, 9, 0), false),
        ];
        for (label, date, pinned) in rows {
            let Some(it) = store::with(|s| s.insert_text(&format!("{label} {}", uuid()), None, &src))
            else {
                continue;
            };
            store::with(|s| s.debug_set_date(date, &it.id));
            if pinned {
                store::with(|s| s.toggle_pin(&it.id, true));
            }
        }
    };
    let survivors = || -> Vec<String> {
        let mut v: Vec<String> = store::read(|s| {
            s.items
                .iter()
                .map(|i| {
                    i.snippet
                        .split_whitespace()
                        .next()
                        .unwrap_or("")
                        .to_string()
                })
                .collect()
        });
        v.sort();
        v
    };
    let p = Preferences::shared();
    let check = |name: &str, now_ts: f64, days: i64, expect: &[&str]| -> bool {
        seed();
        p.set_cleanup_hour(4);
        p.set_retention_days(days);
        retention::sweep(now_ts);
        let once = survivors();
        retention::sweep(now_ts); // idempotent
        let twice = survivors();
        let mut want: Vec<String> = expect.iter().map(|s| s.to_string()).collect();
        want.sort();
        let good = once == want && twice == once;
        println!(
            "{} {name}: [{}]",
            if good { "ok  " } else { "FAIL" },
            once.join(", ")
        );
        good
    };
    let mut ok = true;
    ok = check(
        "08:00 — 3am shutdown, 8am boot: yesterday goes, today's small hours stay",
        at(0, 8, 0),
        1,
        &["yesterdayPinned", "today0001", "today0130", "today0300", "today0900"],
    ) && ok;
    ok = check(
        "03:00 — before cleanup: yesterday still kept, day before goes",
        at(0, 3, 0),
        1,
        &[
            "yesterday",
            "yesterdayPinned",
            "today0001",
            "today0130",
            "today0300",
            "today0900",
        ],
    ) && ok;
    ok = check(
        "04:00 sharp",
        at(0, 4, 0),
        1,
        &["yesterdayPinned", "today0001", "today0130", "today0300", "today0900"],
    ) && ok;
    ok = check(
        "08:00 with 3-day retention: nothing expires",
        at(0, 8, 0),
        3,
        &[
            "dayBefore",
            "yesterday",
            "yesterdayPinned",
            "today0001",
            "today0130",
            "today0300",
            "today0900",
        ],
    ) && ok;
    // Manual delete stays deleted: remove one, sweep, re-open the store from disk.
    seed();
    if let Some(victim) = store::read(|s| {
        s.items
            .iter()
            .find(|i| i.snippet.starts_with("today0900"))
            .cloned()
    }) {
        store::with(|s| s.remove(&victim.id));
        retention::sweep(at(0, 8, 0));
        let root = store::read(|s| s.root.clone());
        let reloaded = ClipStore::new(root);
        let back = reloaded
            .items
            .iter()
            .any(|i| i.snippet.starts_with("today0900"));
        println!(
            "{}",
            if back {
                "FAIL manual delete came back"
            } else {
                "ok   manual delete stays deleted after reload"
            }
        );
        ok = ok && !back;
    }
    // Never: nothing expires, no timer.
    seed();
    p.set_cleanup_hour(4);
    p.set_retention_days(0);
    retention::sweep(at(0, 8, 0));
    retention::reschedule();
    let count = store::read(|s| s.items.len());
    let never_ok = count == 7 && retention::next_fire().is_none();
    if !never_ok {
        println!("FAIL never: all 7 kept, no timer");
    } else {
        println!("ok   never: all 7 kept, no timer");
    }
    ok = ok && never_ok;
    // Timer cadence: with 7-day retention the next check is the oldest
    // unpinned item's day + 7 at X, not tomorrow.
    seed();
    p.set_cleanup_hour(4);
    p.set_retention_days(7);
    retention::reschedule();
    match retention::next_fire() {
        Some(fire) => {
            let expect = set_hour(add_days(start_of_day(at(-2, 15, 0)), 7), 4, 0, 5.0);
            let good = (fire - expect).abs() < 1.0;
            println!(
                "{} 7-day timer fires at {:.0} (expected {:.0})",
                if good { "ok  " } else { "FAIL" },
                fire,
                expect
            );
            ok = ok && good;
        }
        None => {
            println!("FAIL no timer armed");
            ok = false;
        }
    }
    clear_store();
    p.set_retention_days(1);
    println!("{}", if ok { "retention OK" } else { "retention FAILED" });
    ok
}

// MARK: tombstone — delete, then import a copy taken before the deletion

fn copy_dir_all(src: &Path, dst: &Path) -> std::io::Result<()> {
    std::fs::create_dir_all(dst)?;
    for entry in std::fs::read_dir(src)? {
        let entry = entry?;
        let from = entry.path();
        let to = dst.join(entry.file_name());
        if entry.file_type()?.is_dir() {
            copy_dir_all(&from, &to)?;
        } else {
            std::fs::copy(&from, &to)?;
        }
    }
    Ok(())
}

pub fn tombstone() -> bool {
    clear_store();
    let src = Source {
        bundle_id: Some("test".into()),
        name: Some("Test".into()),
    };
    store::with(|s| {
        s.insert_text("alpha", None, &src);
        s.insert_text("beta", None, &src);
        s.insert_text("gamma", None, &src);
    });
    let copy = std::env::temp_dir().join(format!("pastory-copy-{}", uuid()));
    let _ = std::fs::remove_dir_all(&copy);
    let root = store::read(|s| s.root.clone());
    if let Err(e) = copy_dir_all(&root, &copy) {
        println!("copy failed: {e}");
        return false;
    }
    let Some(beta) = store::read(|s| s.items.iter().find(|i| i.snippet == "beta").cloned()) else {
        let _ = std::fs::remove_dir_all(&copy);
        return false;
    };
    store::with(|s| s.remove(&beta.id));
    let scan = match importer::scan(&copy) {
        Ok(s) => s,
        Err(e) => {
            println!("scan failed: {}", e.message());
            let _ = std::fs::remove_dir_all(&copy);
            return false;
        }
    };
    let added = store::with(|s| s.import_entries(scan.entries));
    let back = store::read(|s| s.items.iter().any(|i| i.snippet == "beta"));
    let ok1 = added == 0 && !back;
    println!(
        "{} deleted item stays deleted after importing the old copy (added {}, beta back: {})",
        if ok1 { "ok  " } else { "FAIL" },
        added,
        back
    );
    store::with(|s| s.insert_text("beta", None, &src));
    let fresh = store::read(|s| s.items.iter().any(|i| i.snippet == "beta"));
    println!(
        "{} a fresh copy of the same text is a new item again",
        if fresh { "ok  " } else { "FAIL" }
    );
    clear_store();
    let _ = std::fs::remove_dir_all(&copy);
    ok1 && fresh
}

// MARK: heic — HEIC round trip, hash stability

pub fn heic() -> bool {
    let mut ok = true;
    clear_store();
    // A P3 picture with gradients, so the compression has something to do and
    // the profile matters.
    let w = 1200usize;
    let h = 800usize;
    let Some(space) = cg::CGColorSpace::with_name(Some(unsafe { cg::kCGColorSpaceDisplayP3 })) else {
        return false;
    };
    let Some((png, _image)) = bitmap_png(w, h, &space, |x, _| {
        let v = (x * 255 / w) as u8;
        [v, 102, 255 - v, 255]
    }) else {
        return false;
    };
    let src = Source {
        bundle_id: Some("test".into()),
        name: Some("Test".into()),
    };
    let p = Preferences::shared();
    p.set_image_storage("heic");
    let Some(item) = store::with(|s| s.insert_image(&png, &src, None)) else {
        println!("FAIL insert png");
        return false;
    };
    report(&mut ok, "stored as heic", item.ext == "heic");
    let on_disk = store::read(|s| {
        std::fs::metadata(s.payload_url(&item))
            .map(|m| m.len())
            .unwrap_or(0)
    });
    report(
        &mut ok,
        &format!(
            "heic smaller than png ({}K vs {}K)",
            on_disk / 1024,
            png.len() / 1024
        ),
        on_disk > 0 && (on_disk as usize) < png.len() / 2,
    );
    let back = store::read(|s| s.png(&item));
    let cg_back = back.as_deref().and_then(screenshotter::image_from_png);
    report(
        &mut ok,
        "png(of:) yields PNG at the same size",
        back.as_deref().map(|b| b.starts_with(&[0x89, 0x50, 0x4E, 0x47])) == Some(true)
            && cg_back.as_ref().map(|g| (cg::CGImage::width(Some(&**g)), cg::CGImage::height(Some(&**g)))) == Some((w, h)),
    );
    let name = cg_back
        .as_ref()
        .and_then(|g| cg::CGImage::color_space(Some(&**g)))
        .and_then(|cs| cg::CGColorSpace::name(Some(&cs)))
        .map(|n| n.to_string());
    let want_name = cg::CGColorSpace::name(Some(&space)).map(|n| n.to_string());
    report(
        &mut ok,
        &format!("color space kept ({})", name.as_deref().unwrap_or("nil")),
        name.is_some() && name == want_name,
    );
    let again = store::with(|s| s.insert_image(&png, &src, None));
    report(
        &mut ok,
        "hash is the PNG's, so the same picture dedupes",
        again.map(|a| a.id) == Some(item.id.clone()),
    );
    p.set_image_storage("png");
    let thumb_png = screenshotter::thumbnail(&_image, 300).and_then(|t| screenshotter::png_data(&t));
    let plain = thumb_png.and_then(|tp| store::with(|s| s.insert_image(&tp, &src, None)));
    report(
        &mut ok,
        "png when chosen",
        plain.map(|i| i.ext) == Some("png".into()),
    );
    p.set_image_storage("heic");
    clear_store();
    ok
}

// MARK: writer — text/richtext/image/URL/GIF/files onto the pasteboard

pub fn writer() -> bool {
    let mut ok = true;
    let pb_types = || -> Vec<String> {
        NSPasteboard::generalPasteboard()
            .types()
            .map(|t| t.iter().map(|s| s.to_string()).collect())
            .unwrap_or_default()
    };
    // Text + rich text + the bump marker.
    pasteboard_writer::write_text("hello pastory", Some(b"{\\rtf1ansi\ncaf\\'e9}"), "w-text");
    let t = pb_types();
    report(
        &mut ok,
        "text on board (string + rtf + marker)",
        t.iter().any(|x| x == "public.utf8-plain-text")
            && t.iter().any(|x| x == "public.rtf")
            && t.iter().any(|x| x == "com.cici.snipclip.marker"),
    );
    // A URL string exposes public.url too.
    pasteboard_writer::write_text("https://example.com/pastory", None, "w-url");
    let t = pb_types();
    report(
        &mut ok,
        "url text exposes public.url",
        t.iter().any(|x| x == "public.url"),
    );
    // Image: PNG + TIFF on the board.
    let Some(space) = cg::CGColorSpace::with_name(Some(unsafe { cg::kCGColorSpaceSRGB })) else {
        return false;
    };
    let Some((png, _)) = bitmap_png(40, 30, &space, |_, _| [255, 128, 0, 255]) else {
        println!("FAIL swatch render");
        return false;
    };
    pasteboard_writer::write_image(&png, "w-img");
    let t = pb_types();
    report(
        &mut ok,
        "image on board (png + tiff + marker)",
        t.iter().any(|x| x == "public.png")
            && t.iter().any(|x| x == "public.tiff")
            && t.iter().any(|x| x == "com.cici.snipclip.marker"),
    );
    // GIF goes as moving-picture data.
    pasteboard_writer::write_gif(b"GIF89a\x01\x00\x01\x00\x80\x00\x00\x00\x00\x00\xff\xff\xff;\x00", "w-gif");
    let t = pb_types();
    report(
        &mut ok,
        "gif on board (com.compuserve.gif)",
        t.iter().any(|x| x == "com.compuserve.gif"),
    );
    // Files the way Finder copies them (NSURL + legacy filenames list).
    let f = sample_file();
    pasteboard_writer::write_files(&[f], "w-files");
    let t = pb_types();
    let urls = monitor::read_file_urls(&NSPasteboard::generalPasteboard());
    report(
        &mut ok,
        "files on board (NSFilenamesPboardType + readable objects)",
        t.iter().any(|x| x == "NSFilenamesPboardType") && urls.len() == 1,
    );
    ok
}
